---ACTIVE_OBJECT
SELECT TOP 1000 * FROM "_SYS_REPO"."ACTIVE_OBJECT" 
WHERE OBJECT_SUFFIX = 'calculationview'
and OBJECT_NAME LIKE '%T024%'
AND PACKAGE_ID='SE'

----OBJECT_HISTORY

SELECT * FROM "_SYS_REPO"."OBJECT_HISTORY" 
WHERE OBJECT_SUFFIX = 'calculationview'
and OBJECT_NAME='MARA'
AND PACKAGE_ID='mmmm' 
ORDER BY VERSION_ID ;




SELECT *
FROM 
	"_SYS_BI"."BIMC_PROPERTIES"
WHERE 
   CATALOG_NAME ='SAPERP.SE16'
   AND CUBE_NAME like  '%MBEW%'
